[build]
  publish = "."

[[redirects]]
  from = "/index.php"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/sme-contract-financing"
  to = "/sme-contract-financing.html"
  status = 200
